name: CICD

on:
  push:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven job
      run: mvn -B clean --file pom.xml
  Compile:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven job
      run: mvn -B compile --file pom.xml
  UnitTesting:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      packages: write
    needs: Compile
    steps:
      - run: echo should run unit test
      - name: Checkout code
        uses: actions/checkout@v1
      - name: maven job
        run: mvn -B test --file pom.xml
      - name: Publish unit Testing Job
        uses: EnricoMi/publish-unit-test-result-action@v1.9
        with:
          files: "target/surefire-reports/*.xml"
